name: proyecto_f
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.1.0
  path_provider: ^2.0.12
  url_launcher: ^6.1.7
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  latlong2: ^0.9.1
  english_words: ^4.0.0
  provider: ^6.0.0
  font_awesome_flutter: ^10.0.0  # Para los íconos adicionales como Instagram
  firebase_core: ^2.14.0
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - img/
    - pa_pdfs/
